### ISSUE TITLE
Targeted mAP bug

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1002]
I get the following error when running `scenario_configs/xview_frcnn_targeted.json`:

2021-03-01 16:51:45 7d6057f6ab77 armory.scenarios.base[6] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
File "/workspace/armory/scenarios/base.py", line 77, in evaluate
results = self._evaluate(config, num_eval_batches, skip_benign, skip_attack)
File "/workspace/armory/scenarios/image_classification.py", line 211, in _evaluate
metrics_logger.log_task(adversarial=True, targeted=True)
File "/workspace/armory/utils/metrics.py", line 1083, in log_task
average_precision_by_class = metric.AP_per_class()
File "/workspace/armory/utils/metrics.py", line 952, in AP_per_class
return object_detection_AP_per_class(y_s, y_preds)
File "/workspace/armory/utils/metrics.py", line 594, in object_detection_AP_per_class
iou = _intersection_over_union(pred_box["box"], gt_box["box"])
File "/workspace/armory/utils/metrics.py", line 462, in _intersection_over_union
i <= 1.0 for i in box_2[np.where(box_2 > 0)]
File "<__array_function__ internals>", line 6, in where
File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 480, in __array__
return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by lcadalzo** [comment]
This issue is a result of ART's PyTorch Faster R-CNN overwriting the input `y` variable. Created an [issue](https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/928) in ART.

**Comment by lcadalzo** [comment]
Closing since a fix has been [merged](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/954) into ART 1.6.
