### ISSUE TITLE
Update jpeg compression defences to be compatible with ART 1.6.*

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1059]
The `art_experimental/defences/jpeg_compression_normalized.py` defense uses a `channel_index` kwarg which has since been deprecated in ART, thus causing an error when trying to run the scenario.

When running  `scenario_configs/xview_frcnn_defended.json`:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/base.py", line 84, in evaluate
    config, num_eval_batches, skip_benign, skip_attack, skip_misclassified
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/object_detection.py", line 29, in _evaluate
    skip_misclassified=None,
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/image_classification.py", line 48, in _evaluate
    estimator = load_defense_internal(config["defense"], estimator)
  File "/opt/conda/lib/python3.7/site-packages/armory/utils/config_loading.py", line 197, in load_defense_internal
    defense = load(defense_config)
  File "/opt/conda/lib/python3.7/site-packages/armory/utils/config_loading.py", line 41, in load
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/armory/art_experimental/defences/jpeg_compression_normalized.py", line 27, in __init__
    apply_predict=apply_predict,
TypeError: __init__() got an unexpected keyword argument 'channel_index'
```

**Comment by lcadalzo** [comment]
Closing due to #1060
