### ISSUE TITLE
TypeError running ucf101_baseline_pretrained_pgd_patch.json

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1070]
Running the following command:
```
armory run scenario_configs/ucf101_baseline_pretrained_pgd_patch.json  --check
```

I get the following error:
```
Traceback (most recent call last):
File "/workspace/armory/scenarios/base.py", line 84, in evaluate
config, num_eval_batches, skip_benign, skip_attack, skip_misclassified
File "/workspace/armory/scenarios/video_ucf101_scenario.py", line 48, in _evaluate
classifier, fit_preprocessing_fn = load_model(model_config)
File "/workspace/armory/utils/config_loading.py", line 102, in load_model
model_config["model_kwargs"], model_config["wrapper_kwargs"], weights_path
File "/workspace/armory/baseline_models/pytorch/ucf101_mars.py", line 314, in get_art_model
**wrapper_kwargs,
TypeError: InputFilter object got multiple values for keyword argument 'channels_first'

```

**Comment by lcadalzo** [comment]
Closed with #1092
