### ISSUE TITLE
Failed to export samples 

### ISSUE THREAD

**Issue by sissiok** [twosixlabs/armory#1072]
I was able to export benign and adversarial samples with `export_samples` argument with ARMORY v0.12.3
But with the newest ARMORY v0.13.1, I got the error below:

```
Attack:   0%|                                        | 0/10 [00:15<?, ?it/s]
2021-05-23 19:16:52 spr-gpu04 armory.scenarios.base[3951093] ERROR Encounter
ed error during scenario evaluation.
Traceback (most recent call last):
  File "/home/xiruoliu/Projects/GARD/lib/armory/armory/scenarios/base.py", l
ine 84, in evaluate
    results = self._evaluate(
  File "/home/xiruoliu/Projects/GARD/lib/armory/armory/scenarios/video_ucf10
1_scenario.py", line 210, in _evaluate
    sample_exporter.export(x, x_adv, y, y_pred_adv)
  File "/home/xiruoliu/Projects/GARD/lib/armory/armory/utils/export.py", lin
e 44, in export
    self.export_fn(x, x_adv)
  File "/home/xiruoliu/Projects/GARD/lib/armory/armory/utils/export.py", lin
e 269, in _export_video
    ffmpeg.input(
  File "/home/xiruoliu/Projects/GARD/.venv/lib/python3.8/site-packages/ffmpe
g/_run.py", line 284, in run_async
    return subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'
2021-05-23 19:16:55 spr-gpu04 armory.docker.host_management[3951025] ERROR C
ommand did not finish cleanly
2021-05-23 19:16:55 spr-gpu04 armory.eval.evaluator[3951025] WARNING Cleanin
g up...
2021-05-23 19:16:55 spr-gpu04 armory.eval.evaluator[3951025] INFO Deleting t
mp_dir /home/xiruoliu/.armory/tmp/2021-05-24T021606.062348
2021-05-23 19:16:55 spr-gpu04 armory.eval.evaluator[3951025] INFO Removing o
utput_dir /home/xiruoliu/Projects/GARD/results/2021-05-24T021606.062348 if e
mpty
```

**Comment by ng390** [comment]
Are you running in no-docker mode? If so what is the output of ```which ffmpeg```? If you are running in docker mode, can you provide the output of ```armory exec <FILL_IN_CONTAINER_NAME> -- which ffmpeg```

**Comment by sissiok** [comment]
I am using no-docker mode. Both `which ffmpeg` and `which ffmpeg-python` output nothing, which is strange. Then I tried to install `ffmpeg-python`, and was told `Requirement already satisfied: ffmpeg-python in ./.venv/lib/python3.8/site-packages (0.2.0
)
Requirement already satisfied: future in ./.venv/lib/python3.8/site-packages (from ffmpeg-
python) (0.18.2)
`

**Comment by sissiok** [comment]
The issue is that ffmpeg was not installed in the new machine. Now it is fixed.
