### ISSUE TITLE
Madry training on UCF101

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#1077]
From Richard Xu: I have encountered the following error after adding `madry_trainer_generator` as defense to ucf101_baseline_pretrained_pgd_patch.json. It seems like ucf101 scenario is always using preprocessing_fn_torch , but during adv training it is suppose to use preprocessing_fn_numpy according to armory/baseline_models/pytorch/ucf101_mars.py?

```
2021-05-25 10:18:05 gaila armory.scenarios.base[19315] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
  File "/home/richardkxu/Documents/armory/armory/scenarios/base.py", line 84, in evaluate
    config, num_eval_batches, skip_benign, skip_attack, skip_misclassified
  File "/home/richardkxu/Documents/armory/armory/scenarios/video_ucf101_scenario.py", line 83, in _evaluate
    defense.fit_generator(train_data, **fit_kwargs)
  File "/home/richardkxu/Documents/armory/armory/art_experimental/defences/madry_trainer_generator.py", line 42, in fit_generator
    self.trainer.fit_generator(generator, nb_epochs=nb_epochs, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/defences/trainer/adversarial_trainer.py", line 172, in fit_generator
    x_batch[adv_ids] = attack.generate(x_batch[adv_ids], y=y_batch[adv_ids], **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent.py", line 181, in generate
    return self._attack.generate(x=x, y=y, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/attacks/attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/attacks/evasion/projected_gradient_descent/projected_gradient_descent_pytorch.py", line 218, in generate
    100 * compute_success(self.estimator, x, targets, adv_x, self.targeted, batch_size=self.batch_size),
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/utils.py", line 663, in compute_success
    attack_success = compute_success_array(classifier, x_clean, labels, x_adv, targeted, batch_size)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/utils.py", line 633, in compute_success_array
    adv_preds = np.argmax(classifier.predict(x_adv, batch_size=batch_size), axis=1)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/estimators/classification/classifier.py", line 71, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/estimators/classification/pytorch.py", line 314, in predict
    model_outputs = self._model(torch.from_numpy(x_preprocessed[begin:end]).to(self._device))
  File "/home/richardkxu/anaconda3/envs/mmactionv2-art-armory/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/richardkxu/Documents/adversarial-robustness-toolbox/art/estimators/classification/pytorch.py", line 952, in forward
    x = self._model(x)
  File "/home/richardkxu/anaconda3/envs/mmactionv2-art-armory/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/richardkxu/Documents/armory/armory/baseline_models/pytorch/ucf101_mars.py", line 296, in forward
    x = preprocessing_fn_torch(x)
  File "/home/richardkxu/Documents/armory/armory/baseline_models/pytorch/ucf101_mars.py", line 117, in preprocessing_fn_torch
    raise ValueError(f"frame shape {tuple(video.shape[1:])} not recognized")
ValueError: frame shape (16, 112, 112) not recognized
my config:
"defense": {
        "kwargs": {
            "eps": 0.03,
            "eps_step": 0.008,
            "max_iter": 7,
            "ratio": 0.45
        },
        "module": "armory.art_experimental.defences.madry_trainer_generator",
        "name": "AdversarialTrainerMadryPGD",
        "type": "Trainer"
    },
I also set model "fit"=true,
```

**Comment by davidslater** [comment]
The error is that `module.training` never gets set, so it never goes down this code branch:
https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/pytorch/ucf101_mars.py#L291

**Comment by davidslater** [comment]
Another related issue is that the attack needs to use pytorch preprocessing in order to backprop to the input, so this requires removing this line:
https://github.com/twosixlabs/armory/blob/master/armory/scenarios/video_ucf101_scenario.py#L72

However, that would be problematic for non-adversarial training techniques.

**Comment by davidslater** [comment]
On another note, the `Trainer` in `art_experimental` should probably be removed, since the `fit_generator` functionality is now implemented in ART: https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/art/defences/trainer/adversarial_trainer_madry_pgd.py#L43

**Comment by davidslater** [comment]
Bypassing the above errors, I run into an issue in the MARS code:
```
2021-05-25 22:43:17 a442db3e9715 armory.scenarios.base[7] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
File "/workspace/armory/scenarios/base.py", line 77, in evaluate
results = self._evaluate(config, num_eval_batches, skip_benign, skip_attack)
File "/workspace/armory/scenarios/video_ucf101_scenario.py", line 79, in _evaluate
defense.fit_generator(train_data, **fit_kwargs)
File "/workspace/armory/art_experimental/defences/madry_trainer_generator.py", line 41, in fit_generator
self.trainer.fit_generator(generator, nb_epochs=nb_epochs, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/art/defences/trainer/adversarial_trainer.py", line 176, in fit_generator
self._classifier.fit(x_batch, y_batch, nb_epochs=1, batch_size=x_batch.shape[0], verbose=0, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/classification/classifier.py", line 71, in replacement_function
return fdict[func_name](self, *args, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/classification/pytorch.py", line 370, in fit
model_outputs = self._model(i_batch)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/classification/pytorch.py", line 920, in forward
x = self._model(x)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/workspace/armory/baseline_models/pytorch/ucf101_mars.py", line 296, in forward
return self.model(x)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 149, in forward
return self.module(*inputs, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/armory/tmp/2021-05-25T224239.220830/external/MARS/models/resnext.py", line 167, in forward
x = self.conv1(x)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
result = self.forward(*input, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 573, in forward
self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 3, 7, 7, 7], expected input[1, 16, 240, 320, 3] to have 3 channels, but got 16 channels instead
```

**Comment by davidslater** [comment]
ART now properly sets `torch.nn.Module.training`, so this should be a non-issue.
