### ISSUE TITLE
setting batch size in fit kwargs conflicts with ART's default batch size for adversarial training

### ISSUE THREAD

**Issue by mehussein** [twosixlabs/armory#1144]
https://github.com/twosixlabs/armory/blob/8eb10ac43bf4382d69625d8cef8a3e8cb23d0318/armory/scenarios/multimodal_so2sat_scenario.py#L125

If I set the `batch_size` in my `fit_kwargs` and use adversarial training as a defense, I get this error:

```
2021-09-01 20:31:16 vista15 armory.scenarios.base[117325] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
  File "/<MY ENV PATH>/lib/python3.8/site-packages/armory/scenarios/base.py", line 83, in evaluate
    results = self._evaluate(
  File "/<MY ENV PATH>/lib/python3.8/site-packages/armory/scenarios/multimodal_so2sat_scenario.py", line 125, in _evaluate
    defense.fit_generator(train_data, **fit_kwargs)
  File "/<MY ENV PATH>/lib/python3.8/site-packages/art/defences/trainer/adversarial_trainer.py", line 178, in fit_generator
    self._classifier.fit(x_batch, y_batch, nb_epochs=1, batch_size=x_batch.shape[0], verbose=0, **kwargs)
TypeError: new_fit() got multiple values for keyword argument 'batch_size'
```

Basically, ART already sets the batch size and that conflicts with the setting in `fit_kwargs`.

**Comment by davidslater** [comment]
This is a API inconsistency in ART. I've made a bug report there:
https://github.com/Trusted-AI/adversarial-robustness-toolbox/issues/1609

And I'll close this issue in Armory.
