### ISSUE TITLE
BrokenPipeError when exporting video tracking samples

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1191]
First, add `"export_samples": 1` to the `"scenario"` config in carla_video_tracking config. Then run .e.g  `armory run carla_video_tracking_goturn_advtextures_undefended.json --num-eval-batches 2`

```
Traceback (most recent call last):
  File "/workspace/armory/scenarios/scenario.py", line 342, in evaluate
    results = self._evaluate()
  File "/workspace/armory/scenarios/scenario.py", line 333, in _evaluate
    self.evaluate_all()
  File "/workspace/armory/scenarios/scenario.py", line 246, in evaluate_all
    self.evaluate_current()
  File "/workspace/armory/scenarios/scenario.py", line 318, in evaluate_current
    self.run_attack()
  File "/workspace/armory/scenarios/carla_video_tracking.py", line 75, in run_attack
    self.sample_exporter.export(x, x_adv, y, y_pred_adv)
  File "/workspace/armory/utils/export.py", line 44, in export
    self.export_fn(x, x_adv)
  File "/workspace/armory/utils/export.py", line 320, in _export_video
    benign_process.stdin.write(benign_pixels.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

```

I've also noticed that the error doesn't occur for UCF101 video dataset.

**Comment by lcadalzo** [comment]
Closing due to #1195
