### ISSUE TITLE
fix double image tag in armory interactive

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1317]
reported in Slack

I’m running into an issue depending on how armory is invoked:
    armory launch twosixarmory/pytorch --interactive
works, but
    armory launch pytorch --interactive
fails with this error message:
```
2022-03-15 13:10:58  0s INFO     armory.eval.evaluator:__init__:31 Constructing Evaluator Object
2022-03-15 13:10:58  0s INFO     armory.eval.evaluator:__init__:62 Retrieving Environment Variables
Traceback (most recent call last):
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/images/twosixarmory/pytorch:0.14.5.g2821ae1:0.14.5.g2821ae1/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/bin/armory", line 33, in <module>
    sys.exit(load_entry_point('armory-testbed', 'console_scripts', 'armory')())
  File "/Users/david.slater/git/davidslater/armory/armory/__main__.py", line 808, in main
    func(sys.argv[2:], prog, description)
  File "/Users/david.slater/git/davidslater/armory/armory/__main__.py", line 706, in launch
    rig = Evaluator(config, root=args.root)
  File "/Users/david.slater/git/davidslater/armory/armory/eval/evaluator.py", line 72, in __init__
    kwargs["image_name"] = self.ensure_image_present(image_name)
  File "/Users/david.slater/git/davidslater/armory/armory/eval/evaluator.py", line 86, in ensure_image_present
    docker_client.images.get(name)
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/models/images.py", line 314, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/api/image.py", line 252, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/david.slater/opt/anaconda3/envs/armory-duo-py37/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/images/twosixarmory/pytorch:0.14.5.g2821ae1:0.14.5.g2821ae1/json: Bad Request ("no such image: twosixarmory/pytorch:0.14.5.g2821ae1:0.14.5.g2821ae1: invalid reference format")
````
It seems to be appending the version tag twice

**Comment by mwartell** [comment]
Fixed by e50d400: don't append a version string if image_name already has one.
