### ISSUE TITLE
Make mscoco_frcnn model compatible with tf2

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1330]
To reproduce error, run the following from the `develop` branch:

```
armory run scenario_configs/dapricot_frcnn_masked_pgd.json --check
```

The stacktrace is as follows:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/armory/scenarios/main.py", line 243, in <module>
    skip_misclassified=args.skip_misclassified,
  File "/workspace/armory/scenarios/main.py", line 146, in run_config
    scenario.evaluate()
  File "/workspace/armory/scenarios/scenario.py", line 368, in evaluate
    results = self._evaluate()
  File "/workspace/armory/scenarios/scenario.py", line 358, in _evaluate
    self.load()
  File "/workspace/armory/scenarios/scenario.py", line 245, in load
    self.load_model()
  File "/workspace/armory/scenarios/dapricot_scenario.py", line 80, in load_model
    super().load_model(defended=defended)
  File "/workspace/armory/scenarios/scenario.py", line 98, in load_model
    model, _ = config_loading.load_model(model_config)
  File "/workspace/armory/utils/config_loading.py", line 110, in load_model
    model_config["model_kwargs"], model_config["wrapper_kwargs"], weights_path
  File "/workspace/armory/baseline_models/tf_graph/mscoco_frcnn.py", line 17, in get_art_model
    images = tf.placeholder(
AttributeError: module 'tensorflow' has no attribute 'placeholder'


```

**Comment by davidslater** [comment]
I can replicate. It doesn't impact mnist because that uses `tensorflow.compat.v1.placeholder`.
