### ISSUE TITLE
fix bug when trying to run carla scenario step-by-step

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1354]
To reproduce the error:

```
>>> from armory.scenarios.main import get as get_scenario
>>> s = get_scenario("/armory/tmp/2022-03-22T203253.148375/interactive-config.json").load()
>>> s.next()
>>> s.evaluate_current()
```

This should work, but it yields the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/armory/scenarios/scenario.py", line 346, in evaluate_current
    self.run_attack()
  File "/workspace/armory/scenarios/carla_object_detection.py", line 73, in run_attack
    self.metrics_logger_wrt_benign_preds.update_task(
AttributeError: 'CarlaObjectDetectionTask' object has no attribute 'metrics_logger_wrt_benign_preds'

```

**Comment by davidslater** [comment]
The issue is that `load()` doesn't actually load the CARLA-specific metrics. I have a fix for it.
