### ISSUE TITLE
warp_ctc dependency not available for cuda11?

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1572]
Via email to armory@twosix:

When I try to run a scenario in the container, I get ModuleNotFoundError: No module named 'warpctc_pytorch'. This seems to be a dependency required by ART, but it is not installed in the container. I tried to install warpctc-pytorch manually in the container using pip, but could not find a version that supports CUDA 11.3 that the container requires.

Could you please advise?

If it helps, the complete error is as follows:
```
2022-06-22 20:12:16 51s ERROR    armory.scenarios.scenario:evaluate:397 Encountered error during scenario evaluation.

Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
           │         └ <code object <module> at 0x7f2072bcc660, file "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 1>
           └ <function _run_code at 0x7f21b5553d30>
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
         └ <code object <module> at 0x7f2072bcc660, file "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 1>
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 228, in <module>
    run_config(
    └ <function run_config at 0x7f20719a6700>
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 144, in run_config
    scenario.evaluate()
    │        └ <function Scenario.evaluate at 0x7f2071658e50>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7f21b4c40a90>
> File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 388, in evaluate
    self._evaluate()
    │    └ <function Scenario._evaluate at 0x7f2071658dc0>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7f21b4c40a90>
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 377, in _evaluate
    self.load()
    │    └ <function Scenario.load at 0x7f2071658940>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7f21b4c40a90>
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 271, in load
    self.load_model()
    │    └ <function AutomaticSpeechRecognition.load_model at 0x7f20716d7160>
    └ <armory.scenarios.audio_asr.AutomaticSpeechRecognition object at 0x7f21b4c40a90>
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/audio_asr.py", line 91, in load_model
    super().load_model(defended=defended)
                                └ True
  File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 109, in load_model
    model, _ = config_loading.load_model(model_config)
               │              │          └ {'fit': False, 'fit_kwargs': {'nb_epochs': 20000}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.deep_speech'...
               │              └ <function load_model at 0x7f20719a6160>
               └ <module 'armory.utils.config_loading' from '/opt/conda/lib/python3.8/site-packages/armory/utils/config_loading.py'>
  File "/opt/conda/lib/python3.8/site-packages/armory/utils/config_loading.py", line 109, in load_model
    model = model_fn(
            └ <function get_art_model at 0x7f20716d7550>
  File "/opt/conda/lib/python3.8/site-packages/armory/baseline_models/pytorch/deep_speech.py", line 24, in get_art_model
    return PyTorchDeepSpeech(**wrapper_kwargs)
           │                   └ {'clip_values': [-1, 1], 'pretrained_model': 'librispeech'}
           └ <class 'art.estimators.speech_recognition.pytorch_deep_speech.PyTorchDeepSpeech'>
  File "/opt/conda/lib/python3.8/site-packages/art/estimators/speech_recognition/pytorch_deep_speech.py", line 269, in __init__
    from warpctc_pytorch import CTCLoss

ModuleNotFoundError: No module named 'warpctc_pytorch'
```

**Comment by mwartell** [comment]
The faulting import is inside a conditional at https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/art/estimators/speech_recognition/pytorch_deep_speech.py#L269

This is only referenced inside the ART CI job at https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/.github/actions/deepspeech-v2/Dockerfile#L34. This makes it an undeclared dependency, and only triggers if `version == 2`.  

There is also a deepspeech-v3 directory in ART which is where I'm looking next.

**Comment by mwartell** [comment]
Sent in email to the reporter:

The [code in ART that gave you the import error](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/art/estimators/speech_recognition/pytorch_deep_speech.py#L269) is contained in a conditional and only attempts the import if the Deepspeech version is 2. If it is 3, no part of ART or armory ever attempts to load warpctc_pytorch.  Without seeing your code, is it possible to switch? Based on the [pull request from April 2021](https://github.com/Trusted-AI/adversarial-robustness-toolbox/pull/1107) that added v3 support it might be preferable if possible.

The only place I can find any reference to that package in the rest of [ART is within a CI test](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/301df378b2fdcada23eebfdc8b8a502b018f9bf6/.github/actions/deepspeech-v2/Dockerfile#L34). I am trying to build that for the Armory 0.15.3 base and will let you know if I succeed.

**Comment by mwartell** [comment]
The warp_ctc package referenced by the ART CI test is housed at https://github.com/SeanNaren/warp-ctc. It does not build in the [pytorch/pytorch:1.11.0-cuda11.3-cudnn8-devel](https://hub.docker.com/layers/pytorch/pytorch/pytorch/1.11.0-cuda11.3-cudnn8-devel/images/sha256-9bfcfa72b6b244c1fbfa24864eec97fb29cfafc065999e9a9ba913fa1e690a02?context=explore) container, failing with
```
Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
```

Next, I'm looking back to pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime as specified in the ART CI in the hope that it might illuminate if we can build a cuda11.3 version. I am not hopeful.

**Comment by mwartell** [comment]
Won't fix. This is a pretty narrow corner case that hinges on an [superseded version](https://github.com/SeanNaren/deepspeech.pytorch/releases/tag/v2.0) from three years ago
