### ISSUE TITLE
fix 0.15.4 release build

### ISSUE THREAD

**Issue by mwartell** [twosixlabs/armory#1593]
The build is [currently faulting in the step where it builds armory-testbed](https://github.com/twosixlabs/armory/runs/7286896498?check_suite_focus=true). The failure is because of a complaint from about the version.

**Comment by mwartell** [comment]
The docker/build.py program fails today with the same error outside of CI:
```
Step 14/17 : COPY ./armory /armory-repo/armory/
 ---> b53c9bbd1ac9
Step 15/17 : RUN SETUPTOOLS_SCM_PRETEND_VERSION=${armory_version} /opt/conda/bin/pip install --use-feature=in-tree-build --no-cache-dir .
 ---> Running in 735e453198f8
Processing /armory-repo
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/armory-repo/setup.py'"'"'; __file__='"'"'/armory-repo/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pq12jr9q
         cwd: /armory-repo/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/armory-repo/setup.py", line 33, in <module>
        setup(
      File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.8/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 432, in __init__
        _Distribution.__init__(self, {
      File "/opt/conda/lib/python3.8/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 708, in finalize_options
        ep(self)
      File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 715, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/armory-repo/.eggs/setuptools_scm-7.0.5-py3.8.egg/setuptools_scm/integration.py", line 90, in version_keyword
        _assign_version(dist, config)
      File "/armory-repo/.eggs/setuptools_scm-7.0.5-py3.8.egg/setuptools_scm/integration.py", line 62, in _assign_version
        _version_missing(config)
      File "/armory-repo/.eggs/setuptools_scm-7.0.5-py3.8.egg/setuptools_scm/__init__.py", line 109, in _version_missing
        raise LookupError(
    LookupError: setuptools-scm was unable to detect version for /armory-repo.
    
    Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
    
    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
    ----------------------------------------
WARNING: Discarding file:///armory-repo. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removing intermediate container 735e453198f8
The command '/bin/sh -c SETUPTOOLS_SCM_PRETEND_VERSION=${armory_version} /opt/conda/bin/pip install --use-feature=in-tree-build --no-cache-dir .' returned a non-zero code: 1
```

**Comment by mwartell** [comment]
Related to #1569?

**Comment by christopherwoodall** [comment]
When the container is built, it specifical ignores [.git](https://github.com/twosixlabs/armory/blob/master/.dockerignore) and is unable to pull tags; thus fails. I've started a [branch](https://github.com/christopherwoodall/armory/tree/pep-0518-pyproject.toml) that uses `hatch` as its build system. There is a hook in place to auto-update `VERSION.txt`, and include that file in the wheels/sdist build.
