### ISSUE TITLE
Error running eval5 carla multimodal OD configs

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1719]
I'm running into an error when attempting to run any of the eval 5 carla multimodal OD configs:
```
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_adversarialpatch_defended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_adversarialpatch_undefended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_dpatch_defended.json
scenario_configs/eval5/carla_object_detection/carla_obj_det_multimodal_dpatch_undefended.json
```

The issue occurs when trying to load the saved model weights, full traceback:
```

Traceback (most recent call last):
File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
│         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
│         └ <code object <module> at 0x7fc894c34c90, file "/workspace/armory/scenarios/main.py", line 1>
└ <function _run_code at 0x7fc971cf49d0>
File "/opt/conda/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
│     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
└ <code object <module> at 0x7fc894c34c90, file "/workspace/armory/scenarios/main.py", line 1>
File "/workspace/armory/scenarios/main.py", line 228, in <module>
run_config(
└ <function run_config at 0x7fc893aaac10>
File "/workspace/armory/scenarios/main.py", line 144, in run_config
scenario.evaluate()
│        └ <function Scenario.evaluate at 0x7fc89379f280>
└ <armory.scenarios.carla_object_detection.CarlaObjectDetectionTask object at 0x7fc894915a60>
> File "/workspace/armory/scenarios/scenario.py", line 391, in evaluate
self._evaluate()
│    └ <function Scenario._evaluate at 0x7fc89379f1f0>
└ <armory.scenarios.carla_object_detection.CarlaObjectDetectionTask object at 0x7fc894915a60>
File "/workspace/armory/scenarios/scenario.py", line 380, in _evaluate
self.load()
│    └ <function Scenario.load at 0x7fc89379ed30>
└ <armory.scenarios.carla_object_detection.CarlaObjectDetectionTask object at 0x7fc894915a60>
File "/workspace/armory/scenarios/scenario.py", line 272, in load
self.load_model()
│    └ <function Scenario.load_model at 0x7fc89379e8b0>
└ <armory.scenarios.carla_object_detection.CarlaObjectDetectionTask object at 0x7fc894915a60>
File "/workspace/armory/scenarios/scenario.py", line 109, in load_model
model, _ = config_loading.load_model(model_config)
           │              │          └ {'fit': False, 'fit_kwargs': {}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.carla_multimodality_object_det...
           │              └ <function load_model at 0x7fc893aaa670>
           └ <module 'armory.utils.config_loading' from '/workspace/armory/utils/config_loading.py'>
File "/workspace/armory/utils/config_loading.py", line 109, in load_model
model = model_fn(
        └ <function get_art_model_mm_robust at 0x7fc89379f9d0>
File "/workspace/armory/baseline_models/pytorch/carla_multimodality_object_detection_frcnn_robust_fusion.py", line 199, in get_art_model_mm_robust
model.load_state_dict(checkpoint)
│     │               └ 
OrderedDict([('backbone.feature_nets.depth.body.conv1.weight', tensor([[[[ 1.1745e-02, -9.7413e-03,  3.1476e-04,  ..., -5.127...
│     └ <function Module.load_state_dict at 0x7fc8e7067a60>
└ FasterRCNN(
    (transform): GeneralizedRCNNTransform(
        Normalize(mean=[0.485, 0.456, 0.406, 0.0, 0.0, 0.0], std=[0.229, 0...
File "/opt/conda/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for FasterRCNN:
size mismatch for roi_heads.box_predictor.cls_score.weight: copying a param with shape torch.Size([4, 1024]) from checkpoint, the shape in current model is torch.Size([3, 1024]).
size mismatch for roi_heads.box_predictor.cls_score.bias: copying a param with shape torch.Size([4]) from checkpoint, the shape in current model is torch.Size([3]).
size mismatch for roi_heads.box_predictor.bbox_pred.weight: copying a param with shape torch.Size([16, 1024]) from checkpoint, the shape in current model is torch.Size([12, 1024]).
size mismatch for roi_heads.box_predictor.bbox_pred.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([12]).

```

**Comment by davidslater** [comment]
@jprokos26 this is the 3 versus 4 hard-coded item, yes? Can you point Lucas at the changes we made to make the eval6 scenarios work at the expense of the eval5 ones?

**Comment by lcadalzo** [comment]
i'm able to reproduce the `ValueError: Dataset uses log-depth and is not compatible with this attack
` error message above

**Comment by davidslater** [comment]
I think we'll need to break out different attack modes for the attack for eval5 and eval6. (Probably reusing the old code for the old mode.)

**Comment by davidslater** [comment]
Related to #1670? And this thread? https://github.com/twosixlabs/armory/pull/1628#issuecomment-1273643587

**Comment by lcadalzo** [comment]
The eval 6 data differs from eval 5 in that the depth format is linear rather than log. The attack [makes a note](https://github.com/twosixlabs/armory/blob/v0.16.0/armory/art_experimental/attacks/carla_obj_det_patch.py#L706) that this means it's no longer backwards compatible with the eval 5 data. I've added some logic to the attack in #1720  to instead switch how it handles depth channels depending on whether the depth format is log or linear, in an effort to make the attack backwards compatible
