### ISSUE TITLE
CI Numpy Failures

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1832]
See [here](https://github.com/twosixlabs/armory/actions/runs/3743705462) for example action for how CI is currently failing due to numpy errors, likely resulting from the new numpy 1.24.0 release on 12/18

Bumping to numpy 1.24.0 may not be trivial as I tried installing it in an `--interactive` Armory container and got the following:
```
numba 0.56.2 requires numpy<1.24,>=1.18, but you have numpy 1.24.0 which is incompatible.
```

Then as a result when I ran the scenario I got:
```

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/workspace/armory/scenarios/__init__.py", line 4, in <module>
    from armory import delayed_imports
  File "/workspace/armory/delayed_imports.py", line 42, in <module>
    paths.set_art_data_path()
  File "/workspace/armory/paths.py", line 35, in set_art_data_path
    from art import config
  File "/opt/conda/lib/python3.9/site-packages/art/__init__.py", line 7, in <module>
    from art import attacks
  File "/opt/conda/lib/python3.9/site-packages/art/attacks/__init__.py", line 8, in <module>
    from art.attacks import evasion
  File "/opt/conda/lib/python3.9/site-packages/art/attacks/evasion/__init__.py", line 17, in <module>
    from art.attacks.evasion.brendel_bethge import BrendelBethgeAttack
  File "/opt/conda/lib/python3.9/site-packages/art/attacks/evasion/brendel_bethge.py", line 50, in <module>
    from numba.experimental import jitclass
  File "/opt/conda/lib/python3.9/site-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/opt/conda/lib/python3.9/site-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/opt/conda/lib/python3.9/site-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception

```

**Comment by lcadalzo** [comment]
numba is only used by one specific ART attack `BrendelBethgeAttack` that we don't often use.

```
I have no name!@fc1eda48d498:/workspace$ grep -r "numba" /opt/conda/lib/python3.9/site-packages/art/
/opt/conda/lib/python3.9/site-packages/art/attacks/evasion/brendel_bethge.py:from numba.experimental import jitclass
/opt/conda/lib/python3.9/site-packages/art/attacks/evasion/__init__.py:if importlib.util.find_spec("numba") is not None:
I have no name!@fc1eda48d498:/workspace$ grep -r "numba" armory/     
```

ART only attempts to import numba if `if importlib.util.find_spec("numba") is not None:` (see [here](https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/1.13.0/art/attacks/evasion/__init__.py#L16)), so this error wouldn't occur if this conditional block wasn't being reached. I'm not sure yet where/how/why the Armory image is adding numba, but perhaps if it didn't, this could enable moving to numpy 1.24

**Comment by mwartell** [comment]
CI completed successfully. https://github.com/twosixlabs/armory/actions/runs/3752115310
