### ISSUE TITLE
Dockerhub manifest issue

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#184]
```
$ python -m armory clean
Pulling the latest docker images
Image twosixarmory/tf1:0.4.0 was not found. Downloading...
Traceback (most recent call last):
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/twosixarmory/tf1:0.4.0/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidslater/git/davidslater/armory/armory/__main__.py", line 112, in _pull_docker_images
    docker_client.images.get(image)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/models/images.py", line 316, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/image.py", line 246, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: twosixarmory/tf1:0.4.0: No such image: twosixarmory/tf1:0.4.0")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/images/create?tag=0.4.0&fromImage=twosixarmory%2Ftf1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/davidslater/git/davidslater/armory/armory/__main__.py", line 262, in <module>
    main()
  File "/Users/davidslater/git/davidslater/armory/armory/__main__.py", line 258, in main
    func(sys.argv[2:], prog, description)
  File "/Users/davidslater/git/davidslater/armory/armory/__main__.py", line 191, in clean
    _pull_docker_images(docker_client)
  File "/Users/davidslater/git/davidslater/armory/armory/__main__.py", line 115, in _pull_docker_images
    docker_client.images.pull(image)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/models/images.py", line 445, in pull
    repository, tag=tag, stream=True, **kwargs
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("manifest for twosixarmory/tf1:0.4.0 not found: manifest unknown: manifest unknown")
```

```
$ docker pull twosixarmory/tf1:0.4.0
Error response from daemon: manifest for twosixarmory/tf1:0.4.0 not found: manifest unknown: manifest unknown
$ docker pull twosixarmory/tf1
Using default tag: latest
Error response from daemon: manifest for twosixarmory/tf1:latest not found: manifest unknown: manifest unknown
```

**Comment by seanpmorgan** [comment]
0.4 hasn't been released. Going forward we will make sure that our release branches are published prior to incrementing master version
