### ISSUE TITLE
import datasets outside of docker

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#506]

**Comment by davidslater** [comment]
If host requirements are installed, you can access them this way:
```
>>> from armory.data import datasets
# If you try to load directly, you will likely get this path error:
>>> ds = datasets.mnist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/davidslater/git/davidslater/armory/armory/data/datasets.py", line 244, in mnist
    framework=framework,
  File "/Users/davidslater/git/davidslater/armory/armory/data/datasets.py", line 166, in _generator_from_tfds
    dataset_dir, dataset_name=dataset_name,
  File "/Users/davidslater/git/davidslater/armory/armory/data/datasets.py", line 522, in _cache_dataset
    name=name,
  File "/Users/davidslater/git/davidslater/armory/armory/data/utils.py", line 155, in download_verify_dataset_cache
    os.makedirs(cache_dir, exist_ok=True)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/Users/davidslater/opt/anaconda3/envs/armory/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/armory'
# here is a workaround (we're working on a cleaner way): 
>>> from armory import paths
>>> ds = datasets.mnist(dataset_dir=paths.host().dataset_dir)
>>> x, y = next(ds)
```

**Comment by davidslater** [comment]
For doing training outside of armory, it would be useful to be able to easily import data with minimal external dependencies.

**Comment by joemathai** [comment]
Also, can we decouple the armory download, to have options to download a dataset separately regardless of the associated docker images?

**Comment by davidslater** [comment]
> Also, can we decouple the armory download, to have options to download a dataset separately regardless of the associated docker images?

Can you add that as a separate issue?

**Comment by joemathai** [comment]
issue #511 has been added.
