### ISSUE TITLE
armory download not working

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#632]
Running:

`armory download librispeech_baseline_sincnet.json` fails with:

```
Running bash command: python -c 'import logging; import coloredlogs; coloredlogs.install(20); from armory.data import datasets; from armory.data import model_weights; datasets.download_all("armory-madry/official_scenario_configs/librispeech_baseline_sincnet.json", "all"); model_weights.download_all("armory-madry/official_scenario_configs/librispeech_baseline_sincnet.json", "all")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/armory/data/datasets.py", line 578, in download_all
    for dataset in config["scenario"][scenario]["dataset_name"]:
KeyError: 'dataset_name'
```

**Comment by seanpmorgan** [comment]
Hi @GuillaumeLeclerc so we've not added functionality to download data for any one specific config file. Instead you need to point it toward a scenario_download_config:
https://armory.readthedocs.io/en/latest/getting_started/#installation

```
armory download scenario_download_configs/scenarios-set1.json
```

Closing this, but will open a new issue to add that functionality because it seems quite intutitive.
