### ISSUE TITLE
Fix TORCH_HOME to work in the container

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory#779]
To replicate error, run:
```
armory run scenario_configs/xview_frcnn.json
```

**Comment by lcadalzo** [comment]
related discussion: https://github.com/pytorch/vision/issues/616

**Comment by mwartell** [comment]
[traceback.txt](https://github.com/twosixlabs/armory/files/5394085/traceback.txt)

**Comment by mwartell** [comment]
## Unwinding the stack

  1. the fault is that torch/hub.py is trying to write /.cache when /workspace/.cache is more appropriate
     - or better still /workspace/pytorch/cache for clarity and visibility
  2. checkout v1.6.0 of pytorch to read deployed hub.py (latest is too new)
  3. in torch/hub.py:load_state_dict_from_url() there is an explicit warning to use TORCH_HOME environment
  4. in torch/hub.py:get_dir() comments claim that TORCH_HOME will default to XDG_CACHE_HOME/torch; I suspect
     there is no XDG_HOME or XDG_CACHE_HOME in the container or `~` does not expand
  5. in torch/hub.py:get_dir() global `_hub_dir` may not be set or `_get_torch_home()` returns `''`
  6. torch/hub.py:_get_torch_home uses the environment variables, paraphrasing (because of excess aliasing):
```python
     torch_home = os.path.expanduser(
      os.getenv('TORCH_HOME',
        default=os.path.join(
          os.getenv('XDG_CACHE_HOME',
                  default='~/.cache'),
        'torch')))
```
  7. XDG_CACHE_HOME is almost certain to not be set in the docker context because there is no desktop
  8. The only other reference to XDG_CACHE_HOME is in torch/_appdirs.py:user_cache_dir() where the same default fallback to `~/.cache` is used if CACHE_HOME is not set
  9. therefore, setting `XDG_CACHE_HOME` will likely clear this defect. If it affects other pytorch behavior it could only be for the better since the other use is manifestly wrong.

## traceback

```
Traceback (most recent call last):
File "/workspace/armory/baseline_models/pytorch/xview_frcnn.py", line 47, in get_art_model
model = make_fastrcnn_model(weights_file=weights_file, **model_kwargs)
File "/workspace/armory/baseline_models/pytorch/xview_frcnn.py", line 31, in make_fastrcnn_model
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
File "/opt/conda/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 361, in fasterrcnn_resnet50_fpn
progress=progress)
File "/opt/conda/lib/python3.7/site-packages/torch/hub.py", line 464, in load_state_dict_from_url
os.makedirs(model_dir)
File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.7/os.py", line 213, in makedirs
makedirs(head, exist_ok=exist_ok)
File "/opt/conda/lib/python3.7/os.py", line 223, in makedirs
mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.cache'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/workspace/armory/scenarios/base.py", line 73, in evaluate
results = self._evaluate(config, num_eval_batches, skip_benign)
File "/workspace/armory/scenarios/image_classification.py", line 36, in _evaluate
estimator, _ = load_model(model_config)
File "/workspace/armory/utils/config_loading.py", line 79, in load_model
model_config["model_kwargs"], model_config["wrapper_kwargs"], weights_file
File "/workspace/armory/baseline_models/pytorch/xview_frcnn.py", line 50, in get_art_model
"Tried writing pretrained weights to directory without write "
PermissionError: Tried writing pretrained weights to directory without write permissions. To fix this error, either run the scenario with --root or run in --interactive mode and inside the container set the TORCH_HOME environment variable to a directory with write permissions.
```
