### ISSUE TITLE
Armory 0.12.1 and UCF101 scenario

### ISSUE THREAD

**Issue by dxoigmn** [twosixlabs/armory#843]
I tried running the baseline UCF101 scenario using Armory 0.12.1. This triggers a bug which I believe is in the dataset itself due to the shape check. This bug always triggers on the 333rd example. Output from my console below:

```
$ CUDA_VISIBLE_DEVICES=7 armory run --no-docker source/armory/scenario_configs/ucf101_baseline_pretrained.json
2020-10-23 17:32:29 spr-gpu01 armory.eval.evaluator[179472] INFO Running evaluation script
2020-10-23 17:32:32 spr-gpu01 __main__[179539] WARNING Outputs will be written to /home/ccorneli/Projects/GARD/results/2020-10-24T003229.595509
2020-10-23 17:32:33 spr-gpu01 armory.utils.external_repo[179539] INFO Downloading external repo: yusong-tan/MARS
2020-10-23 17:32:33 spr-gpu01 armory.data.utils[179539] INFO Using available mars_ucf101_v1.pth in Armory `saved_model_dir`
2020-10-23 17:32:33 spr-gpu01 armory.baseline_models.pytorch.ucf101_mars[179539] INFO Loading model... resnext 101
2020-10-23 17:32:36 spr-gpu01 art.estimators.classification.pytorch[179539] INFO Inferred 1 hidden layers on PyTorch classifier.
2020-10-23 17:32:36 spr-gpu01 armory.scenarios.video_ucf101_scenario[179539] INFO Loading test dataset ucf101...
WARNING:tensorflow:From /home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py:224: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

2020-10-23 17:32:36 spr-gpu01 tensorflow[179539] WARNING From /home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py:224: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

2020-10-23 17:32:36.521553: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-10-23 17:32:36.524775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3f:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-10-23 17:32:36.525108: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-23 17:32:36.526769: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-23 17:32:36.528538: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-10-23 17:32:36.528910: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-10-23 17:32:36.530810: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-10-23 17:32:36.531702: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-10-23 17:32:36.535336: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-23 17:32:36.543648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-23 17:32:36.544246: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-10-23 17:32:36.559559: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2494145000 Hz
2020-10-23 17:32:36.564701: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xe3b9cf0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-10-23 17:32:36.564734: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-10-23 17:32:36.570657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3f:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-10-23 17:32:36.570713: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-23 17:32:36.570736: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-23 17:32:36.570758: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-10-23 17:32:36.570781: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-10-23 17:32:36.570802: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-10-23 17:32:36.570823: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-10-23 17:32:36.570845: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-23 17:32:36.581130: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-23 17:32:36.581275: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-23 17:32:36.590669: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-23 17:32:36.590711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-10-23 17:32:36.590726: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-10-23 17:32:36.603504: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10310 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:3f:00.0, compute capability: 6.1)
2020-10-23 17:32:36.606944: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7472df0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-10-23 17:32:36.606982: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-10-23 17:32:36 spr-gpu01 absl[179539] INFO Load dataset info from /home/ccorneli/.armory/datasets/ucf101/ucf101_1/2.0.0
2020-10-23 17:32:36 spr-gpu01 absl[179539] INFO Field info.citation from disk and from code do not match. Keeping the one from code.
2020-10-23 17:32:36 spr-gpu01 absl[179539] INFO Reusing dataset ucf101 (/home/ccorneli/.armory/datasets/ucf101/ucf101_1/2.0.0)
2020-10-23 17:32:36 spr-gpu01 absl[179539] INFO Constructing tf.data.Dataset for split test, from /home/ccorneli/.armory/datasets/ucf101/ucf101_1/2.0.0
2020-10-23 17:32:36.647558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:3f:00.0 name: TITAN Xp computeCapability: 6.1
coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
2020-10-23 17:32:36.647664: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-10-23 17:32:36.647711: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-10-23 17:32:36.647750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-10-23 17:32:36.647787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-10-23 17:32:36.647825: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-10-23 17:32:36.647862: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-10-23 17:32:36.647899: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-10-23 17:32:36.662583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2020-10-23 17:32:36.662637: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-10-23 17:32:36.662657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2020-10-23 17:32:36.662673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2020-10-23 17:32:36.669375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10310 MB memory) -> physical GPU (device: 0, name: TITAN Xp, pci bus id: 0000:3f:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/ccorneli/Projects/GARD/.venv/lib/python3.7/site-packages/tensorflow_datasets/core/features/feature.py:334: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.map_fn(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))
2020-10-23 17:32:36 spr-gpu01 tensorflow[179539] WARNING From /home/ccorneli/Projects/GARD/.venv/lib/python3.7/site-packages/tensorflow_datasets/core/features/feature.py:334: calling map_fn_v2 (from tensorflow.python.ops.map_fn) with back_prop=False is deprecated and will be removed in a future version.
Instructions for updating:
back_prop=False is deprecated. Consider using tf.stop_gradient instead.
Instead of:
results = tf.map_fn(fn, elems, back_prop=False)
Use:
results = tf.nest.map_structure(tf.stop_gradient, tf.map_fn(fn, elems))
2020-10-23 17:32:36 spr-gpu01 armory.scenarios.video_ucf101_scenario[179539] INFO Running inference on benign examples...
Benign:   9%|███████████████████████▌                                     | 333/3783 [24:19<4:12:03,  4.38s/it]
2020-10-23 17:56:56 spr-gpu01 armory.scenarios.base[179539] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
  File "/home/ccorneli/Projects/GARD/source/armory/armory/scenarios/base.py", line 73, in evaluate
    results = self._evaluate(config, num_eval_batches, skip_benign)
  File "/home/ccorneli/Projects/GARD/source/armory/armory/scenarios/video_ucf101_scenario.py", line 106, in _evaluate
    for x, y in tqdm(test_data, desc="Benign"):
  File "/home/ccorneli/Projects/GARD/.venv/lib/python3.7/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py", line 151, in __next__
    return self.get_batch()
  File "/home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py", line 144, in get_batch
    x = self.preprocessing_fn(x)
  File "/home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py", line 317, in wrapped
    x = function(x)
  File "/home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py", line 819, in ucf101_canonical_preprocessing
    check_shapes(batch.shape, (None,) + context.x_shape)
  File "/home/ccorneli/Projects/GARD/source/armory/armory/data/datasets.py", line 798, in check_shapes
    raise ValueError(f"shape {actual} does not match shape {target}")
ValueError: shape (1, 247, 226, 400, 3) does not match shape (None, None, 240, 320, 3)
2020-10-23 17:56:58 spr-gpu01 armory.docker.host_management[179472] ERROR Command did not finish cleanly
2020-10-23 17:56:58 spr-gpu01 armory.eval.evaluator[179472] WARNING Cleaning up...
2020-10-23 17:56:58 spr-gpu01 armory.eval.evaluator[179472] INFO Deleting tmp_dir /home/ccorneli/.armory/tmp/2020-10-24T003229.595509
2020-10-23 17:56:58 spr-gpu01 armory.eval.evaluator[179472] INFO Removing output_dir /home/ccorneli/Projects/GARD/results/2020-10-24T003229.595509 if empty

```

**Comment by davidslater** [comment]
I can duplicate. That is a weird error. I wonder if the dataset is corrupted.

According to the primary website, all videos should be 240x320. Only that video that has a weird shape (226x400).

I'll need to check to see whether this is an error in the original dataset, an error in TFDS, or an error in Armory processing.

**Comment by davidslater** [comment]
I was able to locate the problem - it exists in the original dataset (dimension 226x400, specifically in 4 clips of the same video):
```
v_PommelHorse_g05_c01.avi
v_PommelHorse_g05_c02.avi
v_PommelHorse_g05_c03.avi
v_PommelHorse_g05_c04.avi
```

These correspond to 4 samples in the test portion of our dataset (index, shape):
```
333 (1, 247, 226, 400, 3)
694 (1, 243, 226, 400, 3)
1343 (1, 294, 226, 400, 3)
3218 (1, 251, 226, 400, 3)
```

My inclination is to skip these samples rather than try to resize them. Alternatively, we can relax the dimensions to a variable size and keep the whole dataset. Thoughts?

**Comment by davidslater** [comment]
The more I think of this, the more I'm leaning towards just relaxing the shape check.

**Comment by davidslater** [comment]
Three potential paths:
A) Change the dimension checks from (240, 320) to (None, None) to handle and ignore that. (However, this might mess up the UCF baseline model preprocessing)
B) Add some logic to skip the data samples. (This would require some ugliness added to data processing.)
C) Rebuild the UCF101 dataset without the weird sample. This would require copying and modifying the TFDS building file and recomputing.
