### ISSUE TITLE
Shape error using black box attack

### ISSUE THREAD

**Issue by wangren09** [twosixlabs/armory#892]
When we run the black box attack (hopskipjump attack), we get the following error (We use the Pytorch, but the input is channel last). Any suggestions on this?

Traceback (most recent call last):
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\armory\scenarios\base.py", line 73, in evaluate
    results = self._evaluate(config, num_eval_batches, skip_benign)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\armory\scenarios\image_classification.py", line 174, in _evaluate
    x_adv = attack.generate(x=x, **generate_kwargs)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\evasion\hop_skip_jump.py", line 174, in generate
    clip_max=clip_max,
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\evasion\hop_skip_jump.py", line 210, in _perturb
    x_adv = self._attack(initial_sample[0], x, initial_sample[1], clip_min, clip_max)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\evasion\hop_skip_jump.py", line 339, in _attack
    clip_max=clip_max,
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\evasion\hop_skip_jump.py", line 482, in _compute_update
    samples=eval_samples, target=target, clip_min=clip_min, clip_max=clip_max
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\attacks\evasion\hop_skip_jump.py", line 516, in _adversarial_satisfactory
    preds = np.argmax(self.estimator.predict(samples, batch_size=self.batch_size), axis=1)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\art\estimators\classification\classifier.py", line 71, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\rails.py", line 73, in predict
    output = self._model.predict(torch.from_numpy(x_preprocessed[begin:end]).to(self._device))
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\rails.py", line 160, in predict
    pred_sum = pred_sum + self.aise[i](x)
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\AISE.py", line 386, in __call__
    _,_,_,pla_labs,*_ = self.clonal_expansion(ant)
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\AISE.py", line 368, in clonal_expansion
    ant_tran = self._hidden_repr_mapping(ant.detach())
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\AISE.py", line 216, in _hidden_repr_mapping
    xh = self.model.truncated_forward(self.hidden_layer)(xx.to(self.device))
  File "C:\Users\bravo\PycharmProjects\armory\armory-example\rails.py", line 116, in partial_forward_1
    out_conv1 = F.dropout(F.relu(self.conv1(x)), 0.1, training=self.training)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "c:\users\bravo\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [64, 1, 3, 3], expected input[1, 28, 28, 28] to have 1 channels, but got 28 channels instead

**Comment by tqch** [comment]
Thanks for bringing this problem up @wangren09 After some work, I figured out that the error was caused by the broadcast of the additive noise generated for update by certain black-box attacks such as HopSkipJump and ZOO.
![image](https://user-images.githubusercontent.com/61949428/98232984-5f21ba00-1f2c-11eb-95a7-10d0a3a0a518.png)
![image](https://user-images.githubusercontent.com/61949428/98233053-782a6b00-1f2c-11eb-99ab-79227d8b212e.png)
The random noise uses the input shape specified by the estimator (1x28x28 for channel first). However, since the estimator in our case workaround the channel last restriction by permuting the axes inside the forward pass, this would lead to the conflict when applying the update step to the image itself.
